spring:
  cloud:
    gateway:
      routes:
        - id: add_request_header_route
          uri: https://example.org
          predicates:
            - Path=/ping
#          filters:
#            - AddRequestHeader=X-Request-Red, Blue-{segment}